<?php namespace App;

/**
 * Created by PhpStorm.
 * User: henno
 * Date: 29/10/16
 * Time: 22:24
 */
class Tahvel
{
    static function getJournals()
    {

        $curl_session_key = TAHVEL_SESSION;

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://tahvel.edu.ee/hois_back/journals?lang=ET&onlyMyJournals=true&page=0&size=200&sort=2,+5,+3,asc&studyYear=149');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Pragma: no-cache';
        $headers[] = 'Cache-Control: no-cache';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'X-Xsrf-Token: c0ec75e4-2dba-4c8e-825e-7609c0822740';
        $headers[] = 'X-Requested-With: XMLHttpRequest';
        $headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284';
        $headers[] = 'Sec-Fetch-Site: same-origin';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Referer: https://tahvel.edu.ee/';
        $headers[] = 'Accept-Language: et,en-GB;q=0.9,en-US;q=0.8,en;q=0.7';
        $headers[] = "Cookie: SESSION=$curl_session_key; plumbr_user_tracker=b941a728-4995-2ae0-1e66-96b011d41ee7; __edux_uid=1-amiagyah-kgsd07a8; _gid=GA1.3.1232013302.1604124381; XSRF-TOKEN=c0ec75e4-2dba-4c8e-825e-7609c0822740; taraStateToken=edd136ee-6800-490f-b24e-3a3edf56ad9d; _ga=GA1.1.51157446.1603826697; _ga_V18Q8DRQY8=GS1.1.1604162225.6.1.1604166346.0; plumbr_session_tracker_28yov9=2e9915f9-fa44-4e70-9474-f354c18a98a3|1604168992312";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $result = json_decode($result, true);
        return $result['content'];
    }

    static function updateJournals()
    {
        // Delete all old journals
        q('truncate table journals');

        // Get journals
        $journals = Tahvel::getJournals();

        // Get existing studentGroups
        $groupsByName = Group::getAll('groupCode');

        // Insert journals
        foreach ($journals as $journal) {
            if (!isset($groupsByName[$journal['studentGroups']])) {
                insert('studentGroups', []);
            }
            insert('journals',
                [
                    "id" => $journal["id"],
                    "studentGroups" => $journal["studentGroups"],
                    "nameEt" => $journal["nameEt"],
                    "teachers" => $journal["teachers"],
                    "plannedHours" => $journal["plannedHours"],
                    "usedHours" => $journal["usedHours"],
                    "status" => $journal["status"],
                    "curriculums" => $journal["curriculums"],
                    "isReviewOk" => $journal["isReviewOk"],
                    "reviewDate" => $journal["reviewDate"],
                    "studyYear" => $journal["studyYear"],
                    "studentCount" => $journal["studentCount"],
                    "canEdit" => $journal["canEdit"]
                ]);

            $journalDetails = Tahvel::getJournal($journal['id']);


            foreach ($journalDetails['lessonHours']['capacityHours'] as $capacityHour) {
                foreach (['planned', 'used'] as $hoursType) {

                    $colName = 'capacity' . $capacityHour['capacity'] . $hoursType;

                    // Add col if missing
                    $colExists = get_one("SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = '" . DATABASE_DATABASE . "' AND TABLE_NAME = 'journals' AND COLUMN_NAME = '$colName'");
                    if (!$colExists) {
                        q("ALTER TABLE `journals` ADD `$colName` int NOT NULL default 0");
                    }

                    // Update value
                    update('journals', [
                        $colName => $capacityHour[$hoursType . "Hours"]
                    ], "id = $journalDetails[id]");

                }

            }

        }

        q('truncate table journalEntries');

        foreach ($journals as $journal) {

            $journalEntries = Tahvel::getJournalEntries($journal['id']);

            foreach ($journalEntries as $entry) {
                insert('journalEntries', [
                    'entryDate' => $entry['entryDate'],
                    'nameEt' => $entry['nameEt'],
                    'nameEn' => $entry['nameEn'],
                    'entryType' => $entry['entryType'],
                    'startLessonNr' => $entry['startLessonNr'],
                    'lessons' => $entry['lessons'],
                    'curriculumModuleOutcomes' => $entry['curriculumModuleOutcomes'],
                    'outcomeOrderNr' => $entry['outcomeOrderNr'],
                    'curriculumModule' => $entry['curriculumModule'],
                    'id' => $entry['id'],
                    'teacher' => $entry['teacher'],
                    'moodleGradeItemId' => $entry['moodleGradeItemId'],
                    'journalId' => $journal['id'],
                ]);
            }
        }

    }

    static function getGroups()
    {

        $curl_session_key = TAHVEL_SESSION;

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://tahvel.edu.ee/hois_back/timetables/group/15/149');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Pragma: no-cache';
        $headers[] = 'Cache-Control: no-cache';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'X-Xsrf-Token: c0ec75e4-2dba-4c8e-825e-7609c0822740';
        $headers[] = 'X-Requested-With: XMLHttpRequest';
        $headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284';
        $headers[] = 'Sec-Fetch-Site: same-origin';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Referer: https://tahvel.edu.ee/';
        $headers[] = 'Accept-Language: et,en-GB;q=0.9,en-US;q=0.8,en;q=0.7';
        $headers[] = "Cookie: SESSION=$curl_session_key; plumbr_user_tracker=b941a728-4995-2ae0-1e66-96b011d41ee7; __edux_uid=1-amiagyah-kgsd07a8; _gid=GA1.3.1232013302.1604124381; XSRF-TOKEN=c0ec75e4-2dba-4c8e-825e-7609c0822740; taraStateToken=edd136ee-6800-490f-b24e-3a3edf56ad9d; _ga=GA1.1.51157446.1603826697; _ga_V18Q8DRQY8=GS1.1.1604162225.6.1.1604166346.0; plumbr_session_tracker_28yov9=2e9915f9-fa44-4e70-9474-f354c18a98a3|1604170126118";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);
        $result = json_decode($result, true);
        return $result;
    }

    static function updateGroups()
    {
        // Delete all old journals
        q('truncate table studentGroups');

        // Get groups
        $groups = Tahvel::getGroups();

        // Insert journals
        foreach ($groups as $group) {

            insert('studentGroups', [
                'groupId' => $group['groupId'],
                'groupCode' => $group['groupCode']
            ]);


        }

    }

    static function getJournalEntries($journalId)
    {
        $curl_session_key = TAHVEL_SESSION;

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://tahvel.edu.ee/hois_back/journals/$journalId/journalEntriesByDate?allStudents=false");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Pragma: no-cache';
        $headers[] = 'Cache-Control: no-cache';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'X-Xsrf-Token: c0ec75e4-2dba-4c8e-825e-7609c0822740';
        $headers[] = 'X-Requested-With: XMLHttpRequest';
        $headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284';
        $headers[] = 'Sec-Fetch-Site: same-origin';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Referer: https://tahvel.edu.ee/';
        $headers[] = 'Accept-Language: et,en-GB;q=0.9,en-US;q=0.8,en;q=0.7';
        $headers[] = "Cookie: SESSION=$curl_session_key; plumbr_user_tracker=b941a728-4995-2ae0-1e66-96b011d41ee7; __edux_uid=1-amiagyah-kgsd07a8; _gid=GA1.3.1232013302.1604124381; XSRF-TOKEN=c0ec75e4-2dba-4c8e-825e-7609c0822740; taraStateToken=edd136ee-6800-490f-b24e-3a3edf56ad9d; _ga=GA1.1.51157446.1603826697; _ga_V18Q8DRQY8=GS1.1.1604162225.6.1.1604166346.0; plumbr_session_tracker_28yov9=2e9915f9-fa44-4e70-9474-f354c18a98a3|1604171299279";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $result = json_decode($result, true);
        return $result;
    }

    private static function getJournal($id)
    {
        $curl_session_key = TAHVEL_SESSION;
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, "https://tahvel.edu.ee/hois_back/journals/$id");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

        $headers = array();
        $headers[] = 'Connection: keep-alive';
        $headers[] = 'Pragma: no-cache';
        $headers[] = 'Cache-Control: no-cache';
        $headers[] = 'Accept: application/json, text/plain, */*';
        $headers[] = 'X-Xsrf-Token: c0ec75e4-2dba-4c8e-825e-7609c0822740';
        $headers[] = 'X-Requested-With: XMLHttpRequest';
        $headers[] = 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284';
        $headers[] = 'Sec-Fetch-Site: same-origin';
        $headers[] = 'Sec-Fetch-Mode: cors';
        $headers[] = 'Sec-Fetch-Dest: empty';
        $headers[] = 'Referer: https://tahvel.edu.ee/';
        $headers[] = 'Accept-Language: et,en-GB;q=0.9,en-US;q=0.8,en;q=0.7';
        $headers[] = "Cookie: SESSION=$curl_session_key; plumbr_user_tracker=b941a728-4995-2ae0-1e66-96b011d41ee7; __edux_uid=1-amiagyah-kgsd07a8; _gid=GA1.3.1232013302.1604124381; XSRF-TOKEN=c0ec75e4-2dba-4c8e-825e-7609c0822740; taraStateToken=400bf58e-a411-4a10-9ef9-b67579d991b2; _gat_UA-143928412-1=1; _ga=GA1.1.51157446.1603826697; _ga_V18Q8DRQY8=GS1.1.1604179454.8.1.1604179463.0; plumbr_session_tracker_28yov9=6e208880-968f-163b-57d7-8556ab164352|1604181303277";
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }

        curl_close($ch);

        $result = json_decode($result, true);
        return $result;
    }
}